Fix spelling of LakeFSHook in provider info
Should remove this importerror:

```
ImportError: Module "lakefs_provider.hooks.lakefs_hook" does not define a "LakefsHook" attribute/class
```